### your site title here

title: Jessica Jones
description: behavioral neuroscientist | hhmi gilliam fellow | uw

baseurl: "/" #name of GitHub repository
url: "https://jesmjones.github.io" #custom url to be used instead of GitHub repository
email: jonesjes@uw.edu

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "jessica--jones/" 
#stackoverflow: "#"
github: "jesmjones"
#researchgate: "#"
orcid: "0000-0003-3638-255X"
#quora: "#"
#instagram: "#"
#facebook: "#"
bluesky: "jonesjes.bsky.social"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - circuits.md
      - ABM.md
      - MMpy.md
      - PAWS.md
      - comp_methods.md
      - taste_classifier.md
      - redirect.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
